### ISSUE TITLE
custom width of bars

### ISSUE THREAD

**Issue by sfg** [m-jahn/lattice-tools#8]
This is a feature request for function "panel.errbars()": sometimes it would be helpful to provide the width of the error bars directly, e.g. in case of asymmetric error bars like for rates etc. In these cases argument "error_margin" could be a 2 columns matrix with upper and lower limits.

**Comment by m-jahn** [comment]
good point. There's an option to provide the width/length of error bars directly, but it does not support _different_ width for lower and upper margin respectively.

```
# alternatively, means and error margins can be supplied directly. 
# In this case means are supplied as unique combinations
# of y and x while error_margin is a separate vector with same length as y.
mtcars_means <- data.frame(
  cyl = sort(unique(mtcars$cyl)),
  mpg = with(mtcars, tapply(mpg, cyl, mean)),
  stdev = with(mtcars, tapply(mpg, cyl, sd))
)

# you might have to adjust the yscale as it is determined from the
# range of the y variable only, ignoring the extension through error bars.
xyplot(mpg ~ factor(cyl), mtcars_means,
  error_margin = mtcars_means$stdev,
  ylim = c(9, 36), groups = cyl,
  lwd = 2, pch = 19, cex = 1.5,
  panel = function(x, y, ...) {
    panel.errbars(x, y, ...)
  }
)
```
result: 
https://github.com/m-jahn/lattice-tools/raw/master/vignettes/README_files/figure-gfm/unnamed-chunk-9-4.png
